"""empty message

Revision ID: 882afaea9287
Revises: 
Create Date: 2018-12-09 19:26:48.818969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882afaea9287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('File',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), server_default='默认分类', nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('pub_date', sa.DateTime(), server_default='2018-12-09 19:26:48.631543', nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('authority', sa.Text(), nullable=False),
    sa.Column('download', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=64), server_default='默认状态', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_File_id'), 'File', ['id'], unique=True)
    op.create_table('News',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('pub_date', sa.DateTime(), server_default='2018-12-09 19:26:48.615925', nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('album', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('type', sa.String(length=64), server_default='默认分类', nullable=False),
    sa.Column('status', sa.String(length=64), server_default='默认状态', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_News_id'), 'News', ['id'], unique=True)
    op.create_table('Notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('pub_date', sa.DateTime(), server_default='2018-12-09 19:26:48.631543', nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('type', sa.String(length=64), server_default='默认状态', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notice_id'), 'Notice', ['id'], unique=True)
    op.create_table('People',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=32), nullable=True),
    sa.Column('edu', sa.String(length=32), nullable=True),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('native', sa.String(length=32), nullable=True),
    sa.Column('pho', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('paper', sa.Text(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no')
    )
    op.create_index(op.f('ix_People_id'), 'People', ['id'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=45), server_default='未设置昵称', nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('signin_time', sa.DateTime(), server_default='2018-12-09 19:26:48.615925', nullable=True),
    sa.Column('authority', sa.String(length=16), server_default='default', nullable=False),
    sa.Column('identity', sa.String(length=16), server_default='default', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_People_id'), table_name='People')
    op.drop_table('People')
    op.drop_index(op.f('ix_Notice_id'), table_name='Notice')
    op.drop_table('Notice')
    op.drop_index(op.f('ix_News_id'), table_name='News')
    op.drop_table('News')
    op.drop_index(op.f('ix_File_id'), table_name='File')
    op.drop_table('File')
    # ### end Alembic commands ###
